const CHARACTERS={
 goldship:{name:'골드 쉽',short:'G',difficulty:'★☆☆',hp:76,theme:'물리 · 버리기 · 변칙',desc:'강한 깡딜을 기반으로 손패를 버리거나 비용을 비트는 기행을 섞습니다.',starter:['gs_strike','gs_strike','gs_strike','gs_guard','gs_guard','gs_guard','gs_kick','gs_reload','gs_feint','gs_advance'],pool:['gs_heavy','gs_overrun','gs_reload','gs_feint','gs_trick','gs_sidestep','gs_advance','gs_kick']},
 tachyon:{name:'아그네스 타키온',short:'T',difficulty:'★★☆',hp:68,theme:'시약 · 촉매 · 연쇄반응',desc:'적에게 시약을 축적하고 촉매로 증폭한 뒤 실험을 폭발시킵니다.',starter:['tk_bolt','tk_bolt','tk_bolt','tk_guard','tk_guard','tk_guard','tk_reagent','tk_reagent','tk_catalyst','tk_burst'],pool:['tk_reagent','tk_catalyst','tk_heat','tk_burst','tk_data','tk_overload','tk_failed','tk_barrier']},
 verxina:{name:'베르시나(비르시나)',short:'V',difficulty:'★★★',hp:72,theme:'베르시나 ↔ 비르시나',desc:'공격적인 베르시나 모드와 수비적인 비르시나 모드를 오가며 전환 보너스를 노립니다.',starter:['vx_strike','vx_strike','vx_strike','vx_guard','vx_guard','vx_guard','vx_shift','vx_shift','vx_resolve','vx_crown'],pool:['vx_resolve','vx_crown','vx_offense','vx_defense','vx_counter','vx_persist','vx_dual','vx_shift']}
};

const C={
 gs_strike:{name:'그냥 때려',type:'공격',cost:1,text:'피해 7.',damage:7,tag:'골드 쉽'},
 gs_guard:{name:'받아내기',type:'방어',cost:1,text:'방어 6.',block:6,tag:'골드 쉽'},
 gs_kick:{name:'골쉽 킥',type:'공격',cost:2,text:'피해 16. 무작위 카드 1장을 버린다.',damage:16,discardRandom:1,tag:'전용'},
 gs_reload:{name:'골드 쉽 출항!',type:'스킬',cost:1,text:'손패를 2장까지 버리고 그만큼 +1장 뽑는다.',discardUpTo:2,drawAfterDiscard:1,tag:'덱 회전'},
 gs_feint:{name:'어딜 보냐',type:'스킬',cost:1,text:'적에게 약화 2. 방어 3.',weak:2,block:3,tag:'변칙'},
 gs_advance:{name:'불침함의 진격',type:'공격',cost:2,text:'피해 10. 이번 턴 버린 카드 1장당 +5.',damage:10,discardScale:5,tag:'고유기'},
 gs_heavy:{name:'몸통 박치기',type:'공격',cost:2,text:'피해 19.',damage:19,tag:'물리'},
 gs_overrun:{name:'냅다 들이받기',type:'공격',cost:2,text:'피해 25. 자신도 피해 5.',damage:25,selfDamage:5,tag:'고위험'},
 gs_trick:{name:'기행',type:'스킬',cost:0,text:'무작위 손패 1장의 이번 턴 비용을 0으로.',randomZero:1,tag:'변칙'},
 gs_sidestep:{name:'사이드 스텝',type:'방어',cost:1,text:'방어 9. 다음 드로우 -1.',block:9,nextDraw:-1,tag:'방어'},

 tk_bolt:{name:'마력 방전 실험',type:'공격',cost:1,text:'피해 6.',damage:6,tag:'화학 피해'},
 tk_guard:{name:'실험용 차폐막',type:'방어',cost:1,text:'방어 6.',block:6,tag:'실험'},
 tk_reagent:{name:'실험용 시약',type:'스킬',cost:1,text:'적에게 시약 3.',reagent:3,tag:'시약'},
 tk_catalyst:{name:'촉매 투여',type:'스킬',cost:1,text:'촉매 1. 카드를 1장 뽑는다.',catalyst:1,draw:1,tag:'촉매'},
 tk_burst:{name:'연쇄 반응',type:'공격',cost:2,text:'시약을 모두 소비. 시약 1당 4 피해, 촉매 1당 계수 +1.',burst:true,tag:'폭발'},
 tk_heat:{name:'발열 반응',type:'공격',cost:1,text:'피해 5 + 현재 시약 수치만큼 추가 피해.',damage:5,reagentDamage:1,tag:'반응'},
 tk_data:{name:'데이터 수집',type:'스킬',cost:1,text:'2장 뽑기. 적 시약 5 이상이면 행동력 +1.',draw:2,energyIfReagent:1,tag:'드로우'},
 tk_overload:{name:'과부하',type:'스킬',cost:1,text:'촉매 1 소비. 이번 턴 시약을 부여할 때 2배.',consumeCatalyst:1,doubleReagent:true,tag:'증폭'},
 tk_failed:{name:'실패작',type:'스킬',cost:0,text:'시약 2. 자신에게 취약 1.',reagent:2,selfVulnerable:1,tag:'실험'},
 tk_barrier:{name:'반응성 차폐',type:'방어',cost:1,text:'방어 5 + 촉매 1당 3.',block:5,catalystBlock:3,tag:'방어'},

 vx_strike:{name:'정면 돌파',type:'공격',cost:1,text:'피해 7.',damage:7,tag:'공용'},
 vx_guard:{name:'버텨내기',type:'방어',cost:1,text:'방어 7.',block:7,tag:'공용'},
 vx_shift:{name:'선회',type:'스킬',cost:0,text:'반대 모드로 전환. 카드 1장 뽑기.',shift:true,draw:1,tag:'전환'},
 vx_resolve:{name:'결의',type:'혼합',cost:1,text:'베르시나: 피해 11 / 비르시나: 방어 11.',stanceResolve:11,tag:'모드'},
 vx_crown:{name:'왕관을 향하여',type:'공격',cost:1,text:'피해 7. 이번 턴 모드를 바꿨다면 +10.',damage:7,shiftBonusDamage:10,tag:'전환 보상'},
 vx_offense:{name:'공세 전환',type:'공격',cost:1,text:'베르시나 모드로 전환. 전환했다면 피해 9.',setStance:'offense',damageIfShift:9,tag:'공세'},
 vx_defense:{name:'수세 전환',type:'방어',cost:1,text:'비르시나 모드로 전환. 전환했다면 방어 10.',setStance:'defense',blockIfShift:10,tag:'수세'},
 vx_counter:{name:'견뎌낸 패배',type:'공격',cost:1,text:'피해 6. 지난 적 턴 HP가 줄었다면 +12.',damage:6,hurtLastBonus:12,tag:'집념'},
 vx_persist:{name:'집념',type:'스킬',cost:1,text:'이번 턴 방어 6. 다음 공격 카드 피해 +5.',block:6,nextAttackBonus:5,tag:'집념'},
 vx_dual:{name:'두 이름의 긍지',type:'혼합',cost:2,text:'피해 9, 방어 9. 현재 모드의 강화 효과를 모두 받음.',damage:9,block:9,tag:'고급'}
};


const STORAGE_KEY='uma_spire_v004_content';
let USER_DATA={cards:[],events:[],enemies:[],relics:[]};
const RELICS={};
const SAMPLE_DATA={
 cards:[{id:'custom_gs_headbutt',name:'뜬금없는 박치기',character:'goldship',type:'공격',cost:1,text:'피해 9. 직접 만든 카드 예시.',tag:'사용자 카드',damage:9}],
 events:[{id:'sample_event_lab',title:'반짝이는 서포트 카드',body:'복도 구석에서 아직 주인이 없는 서포트 카드 한 장을 발견했다.',choices:[{text:'가져간다 — 랜덤 유물 획득',effect:'relic',value:1},{text:'그냥 지나간다',effect:'none',value:0}]}],
 enemies:[{id:'sample_enemy',name:'커스텀 모의전 · 보드카',hp:52,pattern:[{t:'attack',v:9},{t:'blockAttack',v:7,b:5},{t:'attack',v:13}]}],
 relics:[{id:'sample_stopwatch',name:'낡은 스톱워치',trigger:'battleStart',effect:'draw',value:1,text:'전투 시작 시 카드를 1장 더 뽑는다.'},{id:'sample_carrot',name:'당근 부적',trigger:'battleEnd',effect:'heal',value:3,text:'전투 승리 시 HP 3 회복.'}]
};
function loadUserData(){try{const saved=localStorage.getItem(STORAGE_KEY);USER_DATA=saved?JSON.parse(saved):structuredClone(SAMPLE_DATA)}catch(e){USER_DATA=JSON.parse(JSON.stringify(SAMPLE_DATA))}syncUserData()}
function saveUserData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(USER_DATA));syncUserData()}
function syncUserData(){USER_DATA.cards.forEach(x=>C[x.id]={...x,cost:+x.cost,damage:+x.damage||0,block:+x.block||0,draw:+x.draw||0,heal:+x.heal||0,energy:+x.energy||0,weak:+x.weak||0,reagent:+x.reagent||0,catalyst:+x.catalyst||0,shift:x.shift===true||x.shift==='true'});Object.keys(RELICS).forEach(k=>delete RELICS[k]);USER_DATA.relics.forEach(x=>RELICS[x.id]=x)}
function triggerRelics(trigger){if(!state||!state.relics)return;state.relics.forEach(id=>{const r=RELICS[id];if(!r||r.trigger!==trigger)return;const v=+r.value||0;if(r.effect==='draw'&&battle)drawCards(v);if(r.effect==='energy'&&battle)battle.energy+=v;if(r.effect==='block'&&battle)gainBlock(v);if(r.effect==='heal')state.hp=Math.min(state.maxHp,state.hp+v);if(battle)battle.log.push(`유물 ${r.name} 발동`)})}
function openRandomEvent(){const defaults=[{title:'수상한 자판기',body:'트레이너실 복도 한가운데 처음 보는 자판기가 놓여 있다.',choices:[{text:'당근주스 구매 — 30G / HP +18',effect:'healBuy',value:18},{text:'정체불명 버튼 — 랜덤 카드 획득',effect:'card',value:1},{text:'무시하고 지나간다',effect:'none',value:0}]}];const pool=[...defaults,...USER_DATA.events];const ev=pool[Math.floor(Math.random()*pool.length)];$('#eventTitle').textContent=ev.title;$('#eventBody').textContent=ev.body;const box=$('#eventActions');box.innerHTML='';ev.choices.forEach(ch=>{const b=document.createElement('button');b.textContent=ch.text;b.className='ghost';b.onclick=()=>applyEventChoice(ch);box.appendChild(b)});show('eventScreen')}
function applyEventChoice(ch){const v=+ch.value||0;if(ch.effect==='healBuy'){if(state.gold>=30){state.gold-=30;state.hp=Math.min(state.maxHp,state.hp+v)}}else if(ch.effect==='heal')state.hp=Math.min(state.maxHp,state.hp+v);else if(ch.effect==='damage')state.hp=Math.max(1,state.hp-v);else if(ch.effect==='gold')state.gold+=v;else if(ch.effect==='card'){const ids=[...CHARACTERS[state.charId].pool,...USER_DATA.cards.filter(x=>x.character===state.charId).map(x=>x.id)];if(ids.length)state.deck.push(ids[Math.floor(Math.random()*ids.length)])}else if(ch.effect==='relic'){const candidates=USER_DATA.relics.filter(r=>!state.relics.includes(r.id));if(candidates.length){const r=candidates[Math.floor(Math.random()*candidates.length)];state.relics.push(r.id)}}renderAll();show('mapScreen')}
function uid(prefix){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`}
function setupDataManager(){const dlg=$('#dataDialog');$('#dataBtn').onclick=()=>{renderDataTab('cards');dlg.showModal()};$('#closeDataBtn').onclick=()=>dlg.close();document.querySelectorAll('.data-tabs button').forEach(b=>b.onclick=()=>renderDataTab(b.dataset.tab))}
function renderDataTab(tab){document.querySelectorAll('.data-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const p=$('#dataPanel');if(tab==='cards')renderCardManager(p);if(tab==='events')renderEventManager(p);if(tab==='enemies')renderEnemyManager(p);if(tab==='relics')renderRelicManager(p);if(tab==='json')renderJsonManager(p)}
function rowHtml(title,sub,i,type){return `<div class="content-row"><div><b>${title}</b><small>${sub}</small></div><div class="content-actions"><button class="danger" data-del="${type}:${i}">삭제</button></div></div>`}
function wireDeletes(type){document.querySelectorAll(`[data-del^="${type}:"]`).forEach(b=>b.onclick=()=>{const i=+b.dataset.del.split(':')[1];USER_DATA[type].splice(i,1);saveUserData();renderDataTab(type)})}
function renderCardManager(p){p.innerHTML=`<div class="manager-note">아래에서 만든 카드는 선택한 캐릭터의 전투 보상 풀에 바로 추가됩니다. 현재 예시는 범용 효과 위주입니다.</div><div class="data-grid"><form id="cardForm" class="data-form"><h4>새 카드</h4><div class="field"><label>이름</label><input name="name" required value="새 카드"></div><div class="form-row"><div class="field"><label>캐릭터</label><select name="character"><option value="goldship">골드 쉽</option><option value="tachyon">아그네스 타키온</option><option value="verxina">베르시나</option></select></div><div class="field"><label>종류</label><select name="type"><option>공격</option><option>방어</option><option>스킬</option><option>혼합</option></select></div></div><div class="form-row"><div class="field"><label>비용</label><input name="cost" type="number" min="0" value="1"></div><div class="field"><label>태그</label><input name="tag" value="사용자 카드"></div></div><div class="form-row"><div class="field"><label>피해</label><input name="damage" type="number" value="0"></div><div class="field"><label>방어</label><input name="block" type="number" value="0"></div></div><div class="form-row"><div class="field"><label>드로우</label><input name="draw" type="number" value="0"></div><div class="field"><label>회복</label><input name="heal" type="number" value="0"></div></div><div class="form-row"><div class="field"><label>시약</label><input name="reagent" type="number" value="0"></div><div class="field"><label>촉매</label><input name="catalyst" type="number" value="0"></div></div><div class="field"><label>설명</label><textarea name="text">사용자가 만든 카드입니다.</textarea></div><button>카드 추가</button></form><div class="data-list"><h4>사용자 카드 ${USER_DATA.cards.length}장</h4>${USER_DATA.cards.map((x,i)=>rowHtml(x.name,`${CHARACTERS[x.character]?.name||x.character} · ${x.cost}코스트 · ${x.text}`,i,'cards')).join('')||'<p class="hint">없음</p>'}</div></div>`;$('#cardForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['cost','damage','block','draw','heal','reagent','catalyst'].forEach(k=>o[k]=+o[k]||0);o.id=uid('card');USER_DATA.cards.push(o);saveUserData();renderDataTab('cards')};wireDeletes('cards')}
function renderEventManager(p){p.innerHTML=`<div class="manager-note">이벤트는 ? 노드에서 기본 이벤트와 함께 무작위로 등장합니다. 예시판에서는 선택지 2개까지 만듭니다.</div><div class="data-grid"><form id="eventForm" class="data-form"><h4>새 이벤트</h4><div class="field"><label>제목</label><input name="title" required value="새 이벤트"></div><div class="field"><label>본문</label><textarea name="body">무언가가 일어났다.</textarea></div>${choiceFields(1)}${choiceFields(2)}<button>이벤트 추가</button></form><div class="data-list"><h4>사용자 이벤트 ${USER_DATA.events.length}개</h4>${USER_DATA.events.map((x,i)=>rowHtml(x.title,x.body,i,'events')).join('')||'<p class="hint">없음</p>'}</div></div>`;$('#eventForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const choices=[1,2].map(n=>({text:f['text'+n],effect:f['effect'+n],value:+f['value'+n]||0})).filter(x=>x.text);USER_DATA.events.push({id:uid('event'),title:f.title,body:f.body,choices});saveUserData();renderDataTab('events')};wireDeletes('events')}
function choiceFields(n){return `<fieldset class="data-form"><legend>선택지 ${n}</legend><div class="field"><label>버튼 문구</label><input name="text${n}" value="${n===1?'선택한다':'지나간다'}"></div><div class="form-row"><div class="field"><label>효과</label><select name="effect${n}"><option value="none">없음</option><option value="heal">HP 회복</option><option value="damage">HP 피해</option><option value="gold">골드 획득</option><option value="card">랜덤 카드</option><option value="relic">랜덤 유물</option></select></div><div class="field"><label>수치</label><input name="value${n}" type="number" value="${n===1?10:0}"></div></div></fieldset>`}
function renderEnemyManager(p){p.innerHTML=`<div class="manager-note">등록한 적은 일반 전투 노드의 후보가 됩니다. 3개 행동을 순서대로 반복합니다.</div><div class="data-grid"><form id="enemyForm" class="data-form"><h4>새 적</h4><div class="field"><label>이름</label><input name="name" value="새 모의전 상대"></div><div class="field"><label>HP</label><input name="hp" type="number" value="50"></div>${[1,2,3].map(n=>`<div class="form-row"><div class="field"><label>${n}행동</label><select name="t${n}"><option value="attack">공격</option><option value="blockAttack">방어+공격</option><option value="debuff">공격+취약</option></select></div><div class="field"><label>공격/방어</label><input name="v${n}" value="${7+n*2}"><input name="b${n}" value="5"></div></div>`).join('')}<button>적 추가</button></form><div class="data-list"><h4>사용자 적 ${USER_DATA.enemies.length}종</h4>${USER_DATA.enemies.map((x,i)=>rowHtml(x.name,`HP ${x.hp} · 행동 ${x.pattern.length}개`,i,'enemies')).join('')||'<p class="hint">없음</p>'}</div></div>`;$('#enemyForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const pattern=[1,2,3].map(n=>({t:f['t'+n],v:+f['v'+n]||0,b:+f['b'+n]||0}));USER_DATA.enemies.push({id:uid('enemy'),name:f.name,hp:+f.hp||50,pattern});saveUserData();renderDataTab('enemies')};wireDeletes('enemies')}
function renderRelicManager(p){p.innerHTML=`<div class="manager-note">유물은 이벤트에서 획득할 수 있습니다. 현재 트리거는 전투 시작 / 턴 시작 / 전투 종료입니다.</div><div class="data-grid"><form id="relicForm" class="data-form"><h4>새 유물</h4><div class="field"><label>이름</label><input name="name" value="새 유물"></div><div class="form-row"><div class="field"><label>발동 시점</label><select name="trigger"><option value="battleStart">전투 시작</option><option value="turnStart">턴 시작</option><option value="battleEnd">전투 종료</option></select></div><div class="field"><label>효과</label><select name="effect"><option value="draw">드로우</option><option value="energy">행동력</option><option value="block">방어</option><option value="heal">HP 회복</option></select></div></div><div class="field"><label>수치</label><input name="value" type="number" value="1"></div><div class="field"><label>설명</label><textarea name="text">조건 충족 시 효과가 발동합니다.</textarea></div><button>유물 추가</button></form><div class="data-list"><h4>사용자 유물 ${USER_DATA.relics.length}개</h4>${USER_DATA.relics.map((x,i)=>rowHtml(x.name,`${x.trigger} · ${x.effect} ${x.value} · ${x.text}`,i,'relics')).join('')||'<p class="hint">없음</p>'}</div></div>`;$('#relicForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));USER_DATA.relics.push({id:uid('relic'),name:f.name,trigger:f.trigger,effect:f.effect,value:+f.value||0,text:f.text});saveUserData();renderDataTab('relics')};wireDeletes('relics')}
function renderJsonManager(p){p.innerHTML=`<div class="manager-note">이 JSON 하나에 사용자 카드·이벤트·적·유물이 모두 들어갑니다. 복사해 보관하거나 다른 버전에 불러올 수 있습니다.</div><textarea id="jsonBox" class="json-box"></textarea><div class="event-actions"><button id="exportJson">현재 데이터 표시</button><button id="downloadJson" class="ghost">JSON 파일 저장</button><label class="file-button">JSON 파일 불러오기<input id="uploadJson" type="file" accept="application/json,.json"></label><button id="importJson" class="ghost">입력 JSON 적용</button><button id="resetJson" class="danger">예시 데이터로 초기화</button></div>`;$('#jsonBox').value=JSON.stringify(USER_DATA,null,2);$('#exportJson').onclick=()=>$('#jsonBox').value=JSON.stringify(USER_DATA,null,2);$('#downloadJson').onclick=()=>{const blob=new Blob([JSON.stringify(USER_DATA,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='uma_spire_content.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#uploadJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#jsonBox').value=r.result};r.readAsText(f)};$('#importJson').onclick=()=>{try{const d=JSON.parse($('#jsonBox').value);if(!d.cards||!d.events||!d.enemies||!d.relics)throw 0;USER_DATA=d;saveUserData();alert('적용했습니다.')}catch(e){alert('JSON 형식을 확인해주세요.')}};$('#resetJson').onclick=()=>{USER_DATA=JSON.parse(JSON.stringify(SAMPLE_DATA));saveUserData();renderDataTab('json')}}
const nodes=[{id:0,x:50,y:91,type:'start',label:'START',next:[1,2]},{id:1,x:34,y:74,type:'battle',label:'전투',next:[3,4]},{id:2,x:66,y:74,type:'event',label:'이벤트',next:[4,5]},{id:3,x:23,y:54,type:'rest',label:'휴식',next:[6]},{id:4,x:50,y:53,type:'battle',label:'전투',next:[6,7]},{id:5,x:77,y:54,type:'battle',label:'전투',next:[7]},{id:6,x:36,y:33,type:'battle',label:'강적',elite:true,next:[8]},{id:7,x:64,y:33,type:'rest',label:'휴식',next:[8]},{id:8,x:50,y:13,type:'boss',label:'G1 보스',boss:true,next:[]}];
let state=null,battle=null;
const $=s=>document.querySelector(s);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function init(){loadUserData();renderCharacterSelect();setupDataManager();show('selectScreen')}
function renderCharacterSelect(){const box=$('#characterGrid');box.innerHTML='';Object.entries(CHARACTERS).forEach(([id,ch])=>{const el=document.createElement('article');el.className='character-choice';el.innerHTML=`<div class="big-portrait ${id}">${ch.short}</div><div class="difficulty">난이도 ${ch.difficulty}</div><h3>${ch.name}</h3><b>${ch.theme}</b><p>${ch.desc}</p><button>이 캐릭터로 시작</button>`;el.querySelector('button').onclick=()=>startRun(id);box.appendChild(el)})}
function startRun(charId){const ch=CHARACTERS[charId];state={charId,hp:ch.hp,maxHp:ch.hp,gold:80,deck:[...ch.starter],relics:[],currentNode:0,cleared:new Set([0]),floor:1};renderAll();show('mapScreen')}
function renderAll(){if(!state)return;const ch=CHARACTERS[state.charId];$('#charLabel').textContent=ch.name;$('#runHp').textContent=`${state.hp}/${state.maxHp}`;$('#gold').textContent=state.gold;$('#floorLabel').textContent=`${state.floor}/6`;$('#sideCharName').textContent=ch.name;$('#charMechanic').innerHTML=`<b>${ch.theme}</b><small>${ch.desc}</small>`;const rl=$('#relicList');if(rl)rl.innerHTML=state.relics.length?state.relics.map(id=>`<span class="relic-chip" title="${RELICS[id]?.text||''}">${RELICS[id]?.name||id}</span>`).join(''):'<span class="hint">아직 없음</span>';renderDeck();renderMap()}
function renderDeck(){const counts={};state.deck.forEach(id=>counts[id]=(counts[id]||0)+1);const types={공격:0,방어:0,스킬:0,혼합:0};state.deck.forEach(id=>{const c=C[id];if(c)types[c.type]=(types[c.type]||0)+1});$('#deckSummary').innerHTML=`카드 ${state.deck.length}장<br>공격 ${types.공격||0} · 방어 ${types.방어||0} · 스킬 ${types.스킬||0} · 혼합 ${types.혼합||0}`;$('#deckList').innerHTML=Object.entries(counts).map(([id,n])=>{const c=C[id]||{name:'삭제된 사용자 카드',text:id};return `<div class="deck-item"><b>${c.name} ×${n}</b><small>${c.text}</small></div>`}).join('')}
function renderMap(){const map=$('#map');map.innerHTML='';nodes.forEach(n=>n.next.forEach(tid=>{const t=nodes.find(x=>x.id===tid),dx=t.x-n.x,dy=t.y-n.y,len=Math.hypot(dx,dy);const e=document.createElement('div');e.className='edge';Object.assign(e.style,{left:n.x+'%',top:n.y+'%',width:len+'%',transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`});map.appendChild(e)}));const available=nodes.find(n=>n.id===state.currentNode).next;nodes.forEach(n=>{const el=document.createElement('div');el.className='node';if(state.cleared.has(n.id))el.classList.add('cleared');if(n.id===state.currentNode)el.classList.add('current');if(available.includes(n.id))el.classList.add('available');el.style.left=n.x+'%';el.style.top=n.y+'%';el.innerHTML=`<span>${({start:'◆',battle:'⚔',event:'?',rest:'☕',boss:'★'})[n.type]}</span><small>${n.label}</small>`;if(available.includes(n.id))el.onclick=()=>enterNode(n);map.appendChild(el)})}
function enterNode(n){state.currentNode=n.id;state.cleared.add(n.id);state.floor=Math.min(6,state.floor+1);if(n.type==='battle'||n.type==='boss')startBattle(n);else if(n.type==='rest'){const before=state.hp;state.hp=Math.min(state.maxHp,state.hp+22);$('#restText').textContent=`HP를 ${state.hp-before} 회복했습니다.`;renderAll();show('restScreen')}else if(n.type==='event')openRandomEvent()}
function startBattle(node){let enemy;if(node.boss)enemy={name:'최종 보스 · 심볼리 루돌프',hp:100,maxHp:100,pattern:[{t:'attack',v:13},{t:'blockAttack',v:8,b:8},{t:'attack',v:18},{t:'debuff',v:10}]};else if(node.elite)enemy={name:'강적 · 나리타 브라이언',hp:74,maxHp:74,pattern:[{t:'attack',v:11},{t:'attack',v:16},{t:'blockAttack',v:8,b:7}]};else{const custom=USER_DATA.enemies.length?USER_DATA.enemies[Math.floor(Math.random()*USER_DATA.enemies.length)]:null;enemy=custom?{name:custom.name,hp:+custom.hp,maxHp:+custom.hp,pattern:custom.pattern}:{name:'모의전 상대',hp:48,maxHp:48,pattern:[{t:'attack',v:8},{t:'blockAttack',v:6,b:6},{t:'attack',v:12}]}}battle={enemy,playerBlock:0,enemyBlock:0,energy:3,nextEnergy:0,nextDraw:0,drawPile:shuffle([...state.deck]),discard:[],exhaust:[],hand:[],tempCost:{},turn:1,weakEnemy:0,vulnerablePlayer:0,discardedThisTurn:0,reagent:0,catalyst:0,doubleReagent:false,stance:'defense',shiftedThisTurn:false,hurtLastTurn:false,nextAttackBonus:0,log:['전투 시작.']};drawCards(5);triggerRelics('battleStart');show('battleScreen');renderBattle()}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function drawCards(n){for(let i=0;i<n;i++){if(!battle.drawPile.length){if(!battle.discard.length)break;battle.drawPile=shuffle([...battle.discard]);battle.discard=[]}battle.hand.push(battle.drawPile.pop())}}
function intent(){return battle.enemy.pattern[(battle.turn-1)%battle.enemy.pattern.length]}
function intentText(i){if(i.t==='attack')return `⚔ 공격 ${i.v}`;if(i.t==='blockAttack')return `🛡 방어 ${i.b} + 공격 ${i.v}`;return `☠ 공격 ${i.v} + 취약 1`}
function effectiveCost(id,idx){const key=idx+'_'+id;return battle.tempCost[key]??C[id].cost}
function renderBattle(){const ch=CHARACTERS[state.charId];$('#playerName').textContent=ch.name;$('#playerPortrait').textContent=ch.short;$('#playerPortrait').className=`portrait placeholder ${state.charId}`;$('#enemyName').textContent=battle.enemy.name;$('#enemyNameCard').textContent=battle.enemy.name;$('#playerHpText').textContent=`${state.hp} / ${state.maxHp}`;$('#playerHpBar').style.width=Math.max(0,state.hp/state.maxHp*100)+'%';$('#enemyHpText').textContent=`${Math.max(0,battle.enemy.hp)} / ${battle.enemy.maxHp}`;$('#enemyHpBar').style.width=Math.max(0,battle.enemy.hp/battle.enemy.maxHp*100)+'%';$('#playerBlock').textContent=battle.playerBlock;$('#enemyBlock').textContent=battle.enemyBlock;$('#energy').textContent=battle.energy;$('#enemyIntent').textContent=intentText(intent());$('#battleLog').textContent=battle.log.slice(-3).join('  ·  ');
 const ps=[];if(battle.vulnerablePlayer)ps.push(`취약 ${battle.vulnerablePlayer}`);if(battle.nextAttackBonus)ps.push(`다음 공격 +${battle.nextAttackBonus}`);$('#playerStatus').innerHTML=ps.map(x=>`<span class="status">${x}</span>`).join('');const es=[];if(battle.weakEnemy)es.push(`약화 ${battle.weakEnemy}`);if(state.charId==='tachyon'&&battle.reagent)es.push(`시약 ${battle.reagent}`);$('#enemyStatus').innerHTML=es.map(x=>`<span class="status">${x}</span>`).join('');renderSpecial();renderHand()}
function renderSpecial(){let html='';if(state.charId==='goldship')html=`<b>이번 턴 버린 카드 ${battle.discardedThisTurn}장</b><small>불침함의 진격 피해 +${battle.discardedThisTurn*5}</small>`;if(state.charId==='tachyon')html=`<b>시약 ${battle.reagent} · 촉매 ${battle.catalyst}</b><small>${battle.doubleReagent?'과부하 활성: 이번 턴 시약 부여 2배':'시약을 쌓고 연쇄 반응으로 폭발'}</small>`;if(state.charId==='verxina'){const off=battle.stance==='offense';html=`<b class="stance ${off?'offense':'defense'}">${off?'베르시나 모드 · 공격':'비르시나 모드 · 수비'}</b><small>${off?'공격 피해 ×1.5 / 받는 피해 ×1.25':'방어 획득 ×1.5 / 받는 피해 ×0.8'}</small>`}$('#specialMeter').innerHTML=html}
function renderHand(){const h=$('#hand');h.innerHTML='';battle.hand.forEach((id,idx)=>{const c=C[id],cost=effectiveCost(id,idx),el=document.createElement('div');el.className='card '+(battle.energy<cost?'unplayable':'');el.innerHTML=`<div class="cost">${cost}</div><div class="type">${c.type}</div><h4>${c.name}</h4><p>${c.text}</p><div class="tag">${c.tag}</div>`;el.onclick=()=>playCard(idx);h.appendChild(el)})}
function enemyDamage(raw){let dmg=raw;if(state.charId==='verxina'&&battle.stance==='offense')dmg=Math.ceil(dmg*1.5);if(battle.nextAttackBonus){dmg+=battle.nextAttackBonus;battle.nextAttackBonus=0}const absorbed=Math.min(battle.enemyBlock,dmg);battle.enemyBlock-=absorbed;battle.enemy.hp-=dmg-absorbed;return dmg-absorbed}
function gainBlock(raw){let b=raw;if(state.charId==='verxina'&&battle.stance==='defense')b=Math.ceil(b*1.5);battle.playerBlock+=b;return b}
function takeDamage(raw){let dmg=raw;if(battle.weakEnemy&&false){}if(battle.vulnerablePlayer)dmg=Math.ceil(dmg*1.5);if(state.charId==='verxina'){if(battle.stance==='defense')dmg=Math.floor(dmg*.8);else dmg=Math.ceil(dmg*1.25)}const absorbed=Math.min(battle.playerBlock,dmg);battle.playerBlock-=absorbed;const hpLoss=dmg-absorbed;state.hp-=hpLoss;return hpLoss}
function setStance(s){const changed=battle.stance!==s;battle.stance=s;if(changed)battle.shiftedThisTurn=true;return changed}
function toggleStance(){return setStance(battle.stance==='offense'?'defense':'offense')}
function playCard(idx){const id=battle.hand[idx],c=C[id],cost=effectiveCost(id,idx);if(battle.energy<cost)return;battle.energy-=cost;let desc=[];
 let dmg=c.damage||0;if(c.discardScale)dmg+=battle.discardedThisTurn*c.discardScale;if(c.reagentDamage)dmg+=battle.reagent*c.reagentDamage;if(c.shiftBonusDamage&&battle.shiftedThisTurn)dmg+=c.shiftBonusDamage;if(c.hurtLastBonus&&battle.hurtLastTurn)dmg+=c.hurtLastBonus;
 if(c.stanceResolve){if(battle.stance==='offense')dmg=c.stanceResolve;else gainBlock(c.stanceResolve)}
 let changed=false;if(c.shift)changed=toggleStance();if(c.setStance)changed=setStance(c.setStance);if(changed&&c.damageIfShift)dmg+=c.damageIfShift;if(changed&&c.blockIfShift)gainBlock(c.blockIfShift);
 if(c.burst){if(battle.reagent>0){const coef=4+battle.catalyst;dmg=battle.reagent*coef;desc.push(`연쇄 반응 ${battle.reagent}×${coef}`);battle.reagent=0}else dmg=0}
 if(dmg){const dealt=enemyDamage(dmg);desc.push(`피해 ${dealt}`)}
 if(c.block)gainBlock(c.block+(c.catalystBlock?battle.catalyst*c.catalystBlock:0));if(c.heal){const before=state.hp;state.hp=Math.min(state.maxHp,state.hp+c.heal);desc.push(`회복 ${state.hp-before}`)}if(c.energy){battle.energy+=c.energy;desc.push(`행동력 +${c.energy}`)}if(c.weak)battle.weakEnemy+=c.weak;if(c.selfDamage)state.hp-=c.selfDamage;if(c.selfVulnerable)battle.vulnerablePlayer+=c.selfVulnerable;if(c.nextEnergy)battle.nextEnergy+=c.nextEnergy;if(c.nextDraw)battle.nextDraw+=c.nextDraw;if(c.nextAttackBonus)battle.nextAttackBonus+=c.nextAttackBonus;
 if(c.reagent){const add=c.reagent*(battle.doubleReagent?2:1);battle.reagent+=add}if(c.catalyst)battle.catalyst+=c.catalyst;if(c.consumeCatalyst){if(battle.catalyst>=c.consumeCatalyst){battle.catalyst-=c.consumeCatalyst;if(c.doubleReagent)battle.doubleReagent=true}else battle.log.push('촉매가 부족해 과부하 효과가 발동하지 않았다.')}
 battle.hand.splice(idx,1);battle.discard.push(id);delete battle.tempCost[idx+'_'+id];
 if(c.discardRandom&&battle.hand.length){const r=Math.floor(Math.random()*battle.hand.length);battle.discard.push(battle.hand.splice(r,1)[0]);battle.discardedThisTurn++;desc.push('무작위 1장 버림')}
 if(c.discardUpTo){const n=Math.min(c.discardUpTo,battle.hand.length);for(let k=0;k<n;k++){battle.discard.push(battle.hand.shift());battle.discardedThisTurn++}drawCards(n+(c.drawAfterDiscard||0));desc.push(`${n}장 버리고 ${n+(c.drawAfterDiscard||0)}장 드로우`)}
 if(c.randomZero&&battle.hand.length){const r=Math.floor(Math.random()*battle.hand.length);const rid=battle.hand[r];battle.tempCost[r+'_'+rid]=0;desc.push(`${C[rid].name} 비용 0`)}
 if(c.draw)drawCards(c.draw);if(c.energyIfReagent&&battle.reagent>=5){battle.energy+=c.energyIfReagent;desc.push('행동력 +1')}
 battle.log.push(`${c.name}: ${desc.join(', ')||'효과 발동'}`);if(battle.enemy.hp<=0)return winBattle();if(state.hp<=0)return loseGame();renderBattle();renderAll()}
function endTurn(){battle.discard.push(...battle.hand.splice(0));battle.tempCost={};battle.enemyBlock=0;const i=intent();let dmg=i.v||0;if(battle.weakEnemy)dmg=Math.floor(dmg*.75);if(i.b)battle.enemyBlock+=i.b;const before=state.hp;if(dmg)takeDamage(dmg);const lost=Math.max(0,before-state.hp);battle.hurtLastTurn=lost>0;if(battle.weakEnemy)battle.weakEnemy--;if(battle.vulnerablePlayer)battle.vulnerablePlayer--;if(i.t==='debuff')battle.vulnerablePlayer+=1;battle.log.push(`${battle.enemy.name}: ${intentText(i)}${lost?` → HP ${lost} 감소`:''}`);if(state.hp<=0)return loseGame();battle.playerBlock=0;battle.turn++;battle.energy=3+battle.nextEnergy;battle.nextEnergy=0;battle.discardedThisTurn=0;battle.doubleReagent=false;battle.shiftedThisTurn=false;const drawN=Math.max(1,5+battle.nextDraw);battle.nextDraw=0;drawCards(drawN);triggerRelics('turnStart');renderBattle();renderAll()}
function winBattle(){state.gold+=25;triggerRelics('battleEnd');renderAll();const custom=USER_DATA.cards.filter(x=>x.character===state.charId).map(x=>x.id);const pool=shuffle([...CHARACTERS[state.charId].pool,...custom]).slice(0,3),box=$('#rewardCards');box.innerHTML='';pool.forEach(id=>{const c=C[id],el=document.createElement('div');el.className='card';el.innerHTML=`<div class="cost">${c.cost}</div><div class="type">${c.type}</div><h4>${c.name}</h4><p>${c.text}</p><div class="tag">${c.tag}</div>`;el.onclick=()=>{state.deck.push(id);afterReward()};box.appendChild(el)});show('rewardScreen')}
function afterReward(){if(nodes.find(n=>n.id===state.currentNode).boss)return finishRun();renderAll();show('mapScreen')}
function finishRun(){$('#gameOverTitle').textContent='시제품 클리어';$('#gameOverText').textContent=`${CHARACTERS[state.charId].name}로 클리어했습니다. 최종 HP ${state.hp}/${state.maxHp}, 덱 ${state.deck.length}장.`;show('gameOverScreen')}
function loseGame(){$('#gameOverTitle').textContent='도전 실패';$('#gameOverText').textContent=`${CHARACTERS[state.charId].name}의 HP가 0이 되었습니다.`;show('gameOverScreen')}
$('#endTurnBtn').onclick=endTurn;$('#skipRewardBtn').onclick=afterReward;$('#restContinueBtn').onclick=()=>show('mapScreen');$('#restartBtn').onclick=()=>{state=null;battle=null;$('#charLabel').textContent='-';$('#runHp').textContent='-';$('#gold').textContent='-';$('#floorLabel').textContent='-';show('selectScreen')};$('#viewDeckBtn').onclick=()=>$('#deckDialog').showModal();$('#closeDeckBtn').onclick=()=>$('#deckDialog').close();init();
